# Generated by Django 4.2.7 on 2023-11-21 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customer_my_pharmacist_customer_my_pharmacist'),
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalInformation',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='medical_information', serialize=False, to='accounts.customer')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('personal_diagnosis', models.CharField(blank=True, choices=[('TB', 'Tuberculosis'), ('DIABETES', 'Diabetes'), ('STROKE', 'Stroke'), ('HEART-DISEASE', 'Heart-Disease'), ('CANCER', 'Cancer'), ('OBESITY', 'Obesity'), ('ANAEMIA', 'Anaemia'), ('ASTHMA', 'Asthma'), ('THYROID-DISORDERS', 'Thyroid-Disorders'), ('NONE', 'None'), ('I DON"T KNOW', 'I don"t know')], max_length=20, null=True)),
                ('family_diagnosis', models.CharField(blank=True, choices=[('TB', 'Tuberculosis'), ('DIABETES', 'Diabetes'), ('STROKE', 'Stroke'), ('HEART-DISEASE', 'Heart-Disease'), ('CANCER', 'Cancer'), ('OBESITY', 'Obesity'), ('ANAEMIA', 'Anaemia'), ('ASTHMA', 'Asthma'), ('THYROID-DISORDERS', 'Thyroid-Disorders'), ('NONE', 'None'), ('I DON"T KNOW', 'I don"t know')], max_length=20, null=True)),
            ],
        ),
    ]
