# Generated by Django 4.2.7 on 2023-11-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_medicalinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalinformation',
            name='write_message_to_pharmacist',
            field=models.TextField(blank=True, null=True),
        ),
    ]
