# Generated by Django 4.2.7 on 2023-11-14 09:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_customer_user_alter_pharmacist_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID' )),
                ('medicine_name', models.TextField()),
                ('description', models.TextField()),
                ('unitVolume', models.CharField(max_length=50)),
                ('pricePerUnitVolume', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pharmacist', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.pharmacist')),
            ],
        ),
    ]
