# Generated by Django 4.2.7 on 2023-11-15 13:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customer_user_alter_pharmacist_user'),
        ('Pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_legalName', models.CharField(max_length=100)),
                ('supplier_TradeName', models.CharField(max_length=100)),
                ('supplier_GSTReGNo', models.CharField(max_length=60)),
                ('category', models.CharField(choices=[('Organization', 'Organization'), ('Individual', 'Individual')], max_length=50)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_PhoneNumber', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_address1', models.CharField(max_length=50)),
                ('settlement_currency', models.CharField(max_length=100)),
                ('payment_method', models.CharField(choices=[('Cheque', 'Cheque'), ('EFT', 'EFT')], max_length=50)),
                ('contract_startDate', models.DateTimeField()),
                ('contract_EndDate', models.DateTimeField()),
                ('contract_Document', models.FileField(upload_to='')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pharmacist', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.pharmacist')),
            ],
        ),
    ]
