# Generated by Django 4.2.7 on 2023-11-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0002_addsupplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addsupplier',
            name='contract_EndDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='addsupplier',
            name='contract_startDate',
            field=models.DateField(),
        ),
    ]
