# Generated by Django 4.2.7 on 2023-11-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0002_alter_addmedicine_expirydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmedicine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medicine_images/'),
        ),
    ]
