# Generated by Django 4.2.7 on 2023-11-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_my_pharmacist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='my_pharmacist',
        ),
        migrations.AddField(
            model_name='customer',
            name='my_pharmacist',
            field=models.ManyToManyField(blank=True, to='accounts.pharmacist'),
        ),
    ]
