# Generated by Django 4.2.7 on 2023-11-20 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customer_my_pharmacist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='my_pharmacist',
        ),
        migrations.AddField(
            model_name='customer',
            name='my_pharmacist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_customers', to='accounts.pharmacist'),
        ),
    ]
